// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xfqjnvoixvucasaazsxq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhmcWpudm9peHZ1Y2FzYWF6c3hxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI4OTA0MzYsImV4cCI6MjA1ODQ2NjQzNn0.MaD0J3sj2rQiNeDf4tZOocllau2VH36WVe374beNPr0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);